- name: Add pg12 repo
  ansible.builtin.shell:
    cmd: yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  become: True

- name:  disable pg
  ansible.builtin.shell:
    cmd:  dnf -qy module disable postgresql
  become: True

- name:  install pg 12
  ansible.builtin.shell:
    cmd:  dnf -y install postgresql12 postgresql12-server
  become: True

- name: Stop service postgres, if not stopped
  ansible.builtin.service:
    name: postgresql-12 
    state: stopped
    enabled: yes
  become: True   

- name: destroy database
  ansible.builtin.shell:
    cmd: rm -fr  /var/lib/pgsql/12/data/
  become: True
  
  
- name: "are we new"
  find: paths=/var/lib/pgsql/12/data/ file_type=directory patterns="*"
  register: dir_files
  become: True

- name:  run initdb
  ansible.builtin.shell:
    cmd: /usr/pgsql-12/bin/postgresql-12-setup initdb
  when: dir_files.matched|int == 0
  become: True

- name: Pause for 5 seconds to settle
  pause:
    seconds: 5

- name: Start service postgres, if not started
  ansible.builtin.service:
    name: postgresql-12 
    state: started
    enabled: yes
  become: True   

- name:  run  create postgres user
  ansible.builtin.shell:
    cmd: createuser awx
  when: dir_files.matched|int == 0
  become: True
  become_user: postgres

- name: create postgress db
  ansible.builtin.shell:
    cmd: createdb awx -O awx
  when: dir_files.matched|int == 0
  become: True
  become_user: postgres

- name: set password 
  ansible.builtin.shell:
    cmd: psql -c "ALTER USER awx PASSWORD '{{ awx_db_password }}';"
  when: dir_files.matched|int != 0
  become: True
  become_user: postgres
  
- name: create postgress access
  ansible.builtin.template:
    src: templates/pg_hba.conf.j2
    dest: /var/lib/pgsql/12/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0600'
  become: True

- name: create postgress credentials
  ansible.builtin.template:
    src: templates/credentials.py.j2
    dest: /etc/tower/conf.d/postgres.py
    owner: awx
    group: awx 
    mode: '0600'
  become: True
