- name: install redis
  action: template src=dumpall.j2 dest=/tmp/ansible_dump.all

- name: adding existing user cloud-user to group sudo
  user:
    name: 'awx'
    groups: redis
    append: yes
  become: True

- name: enable socket in redist
  template:
    src:  redis.conf.j2
    dest: /etc/redus.conf
    force: yes
    mode: '0644'
    owner: root
    group: root
  become: True


- name: Start service redis, if not started
  ansible.builtin.service:
    name: redis
    state: started
  become: True
